**

!/deployment/frontend/Caddyfile
!/package.json
!/package-lock.json
!/public/
!/src/
!/third-party/aig-hagen/aig_graph_component/*.tgz
!/third-party/ctan.org/
!/third-party/xai-ca/
!/env.d.ts
!/index.html
!/tsconfig*.json
!/vite.config.ts
