services:
  frontend:
    image: aig-hagen/argumentation-toolbox-frontend:latest
    pull_policy: build
    build:
      context: ..
      dockerfile: ./deployment/frontend/Dockerfile
    platform: linux/amd64
    ports:
      - "8082:8080"
    environment:
      TWEETYPROJECT_BACKEND_BASE_URL: http://backend:8080
    depends_on:
      - backend

  backend:
    image: aig-hagen/argumentation-toolbox-backend:latest
    pull_policy: build
    build:
      context: ..
      dockerfile: ./deployment/backend/Dockerfile
    platform: linux/amd64